version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis_broker
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: fastapi_app
    # FIX: Changed 'uuvicorn' to 'uvicorn'
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env # Load environment variables from .env file
    depends_on:
      - redis

  worker:
    build: .
    container_name: celery_worker
    # Command is correct for Celery worker
    command: celery -A worker.celery_worker.celery_app worker --loglevel=info
    env_file:
      - .env # Load environment variables from .env file
    depends_on:
      - redis
      - app # Depends on app to ensure database setup if any, though not strictly required for Celery itself

  beat:
    build: .
    container_name: celery_beat
    # Command is correct for Celery beat
    command: celery -A worker.celery_worker.celery_app beat --loglevel=info
    env_file:
      - .env # Load environment variables from .env file
    depends_on:
      - redis
      - app